### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by mghaigh** [graphql-java/graphql-java-spring#11]
My Graphql-Java server is working fine and queries work fine through Insomnia. However I am trying to use React/Relay as the client and I am getting the following error message from my React App
Access to fetch at 'http://localhost:8080/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Do you know how I can set-up my GraphQL server to respond correctly?
Thanks, Martin

**Comment by marceloverdijk** [comment]
@mghaigh I haven't tried myself but see https://spring.io/guides/gs/rest-service-cors/

```
    @Bean
    public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurerAdapter() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping("/graphql").allowedOrigins("http://localhost:3000");
            }
        };
    }
```

**Comment by andimarek** [comment]
@mghaigh did the solution from @marceloverdijk solve your problem?

**Comment by alexkeshav** [comment]
Yes it did solved for me , By defining the global cross origin setting like @marceloverdijk said.

Also , below snippet removing use of deprecated Adapter  WebMvcConfigurerAdapter.
we can use WebMvcConfigurer interface and override its default method addCorsMappings ,

Hard coded mapping "/graphql"  should be replaced with  ${graphql.url:graphql} 

    @Value("${graphql.url:graphql}")
    private String graphqlurl;
    /*
     * No cors origin global setting.
     */
    @Bean
    public WebMvcConfigurer corsConfigurer() {

        return new WebMvcConfigurer() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping(graphqlurl).allowedOrigins("http://localhost:3000");
            }
        };
    }

**Comment by alexkeshav** [comment]
Hard coded mapping "/graphql"  should be replaced with  ${graphql.url:graphql}  
    @Value("${graphql.url:graphql}")
    private String graphqlurl;
    /*
     * No cors origin global setting.
     */
    @Bean
    public WebMvcConfigurer corsConfigurer() {

        return new WebMvcConfigurer() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping(graphqlurl).allowedOrigins("http://localhost:3000");
            }
        };
    }

**Comment by Ustimov** [comment]
One can just use the **homepage** property of the **create-react-app** configuration [https://facebook.github.io/create-react-app/docs/deployment#building-for-relative-paths](https://facebook.github.io/create-react-app/docs/deployment#building-for-relative-paths).

**Comment by cebartling** [comment]
@alexkeshav and @marceloverdijk Thanks for sharing the CORS configurer solution. Works great!

**Comment by gavin-haynes-grow** [comment]
I had to register a CORS filter as in https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/8

You can use it with the graphql.url property like

```
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.web.cors.CorsConfiguration;
import org.springframework.web.cors.UrlBasedCorsConfigurationSource;
import org.springframework.web.filter.CorsFilter;

...

    @Value("${graphql.url:/graphql}")
    private String graphqlurl;

    @Bean
    public FilterRegistrationBean<CorsFilter> corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("*");
        config.addAllowedHeader("*");
        config.addAllowedMethod("*");
        source.registerCorsConfiguration(graphqlurl, config);
        FilterRegistrationBean<CorsFilter> bean = new FilterRegistrationBean<>(new CorsFilter(source));
        bean.setOrder(0);
        return bean;
    }
```

(note the added slash in the graphql path)

**Comment by andimarek** [comment]
This project is now archived in favor of the official [Spring GraphQL](https://github.com/graphql-java/graphql-java-spring) integration.
