### ISSUE TITLE
Multipart upload

### ISSUE THREAD

**Issue by jakubbrodzinski** [graphql-java/graphql-java-spring#14]
I used this depenendy in my app and everything worked just fine, until I decided to add uploading files feature.  I have read that this feature is already implemented in
https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/102
so I declared the new Scalar (in schema and in `RuntimeWiring` configuration `.scalar(ApolloScalars.Upload)`). Sadly when I try to POST with the file
`curl  http://localhost:8080/graphql \
  -F operations='{ "query": "mutation ($file: Upload!) { singleUpload(file: $file) { id } }", "variables": { "file": null } }' \
  -F map='{ "0": ["variables.file"] }' \
  -F 0=@t1.txt`
I get
` {"timestamp":"2019-05-19T16:31:05.151+0000","status":415,"error":"Unsupported Media Type","message":"Content type 'multipart/form-data;boundary=------------------------07182a3f39beb5b0;charset=UTF-8' not supported","path":"/graphql"}`
I figured out that it was because `@GraphQLController` from this repository only consumes JSON and not multipart/form-data. Do you have any suggestions how to solve it?

**Comment by marceloverdijk** [comment]
@jakubbrodzinski `graphql-java-kickstart` is not `graphql-java-spring`. The latter does not support multipart upload (yet).

**Comment by heruan** [comment]
@andimarek I've seen many issues on `graphql-java` about file upload support being closed as "not in scope" and I agree on that. This Spring Boot integration though seems the right place to implement support, dealing with servlets and such.

Do you have any plans for this? I'd like to contribute to it if it's of interest.

**Comment by jakubbrodzinski** [comment]
@heruan around 2 months ago i forked `graphql-java-spring` repo and added my file upload implementation (with few tests included). It actually worked out for me and I used it in one of my projects (`Angular` with `Apollo` module on front and `Spring Boot` with `GraphQL` on backend). Check it out.
https://github.com/jakubbrodzinski/graphql-java-spring/tree/multipart_file

**Comment by AnkBurov** [comment]
@jakubbrodzinski maybe you could a pull request to the upstream?

**Comment by AnkBurov** [comment]
Oh, I see that you already did. Nevermind. Thanks though!

**Comment by rogeraime** [comment]
Hi,
 someone here know how to write a operations's query in Multipart using Insomnia for testing single file upload? I write my own but did not work and I received : 
{
  "timestamp": 1602774721435,
  "status": 422,
  "error": "Unprocessable Entity",
  "message": "",
  "path": "/graphql"
`}
hier is my query : 
{
  "query": "mutation ($numberPlate: String, $country: $String, $file: Upload) {createTicket(numberPlate: $numberPlate, country:  $country, file: $file)}{ id, timestamp}",
  "variables": {
    "numberPlate": "33333",
    "country": "xyz",
    "file": null
  }
}
Thk you in advance!

![att1](https://user-images.githubusercontent.com/61559462/96224970-a7366800-0f90-11eb-985a-56941e57d5f7.PNG)
![att2](https://user-images.githubusercontent.com/61559462/96224993-af8ea300-0f90-11eb-90c4-1b3690a58ded.PNG)

**Comment by ayush11-11** [comment]
Bad POST multipart request: no part named "graphql" or "query" getting this while sending response through potman

**Comment by andimarek** [comment]
This project is now archived in favor of the official [Spring GraphQL](https://github.com/graphql-java/graphql-java-spring) integration.
