### ISSUE TITLE
graphql query methond mapping 

### ISSUE THREAD

**Issue by songzeyang1024** [graphql-java/graphql-java-spring#15]
I am trying to introduce graphql from my project ,
now , who can tell can  me ,how to implement mapping my function with graphql
just like  resultful

Code :
    public CustomerEntity getCustomer(String account) {
         CustomerEntity customerEntity = this.customerMapper.selectByAccount(account);
         if (null == customerEntity.getAccount()) {
            return null;
        }
        if (customerEntity.getCustomerStatus() > 9) {
            return null;
        }
        return customerEntity;
     }

**Comment by songzeyang1024** [comment]
I am using it now SpringBoot

**Comment by xyombo** [comment]
You can learn from : https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/ 

As your codes, i think you need to understand the **DataFetcher**

**Comment by andimarek** [comment]
This project is now archived in favor of the official [Spring GraphQL](https://github.com/graphql-java/graphql-java-spring) integration.
