### ISSUE TITLE
Header Content-Type contains "application/json" not work

### ISSUE THREAD

**Issue by gysbtzs2008** [graphql-java/graphql-java-spring#16]
I post a request with header "Content-Type: application/json; charset=utf-8", and it returns 422 Http Code.
Now the controller only accept Content-Type strictly equals to "application/json" Can it support more dynamic Content-Type header? 

https://github.com/graphql-java/graphql-java-spring/blob/612d644c0002b0aa1aa378b5664e3cc609c7fa0f/graphql-java-spring-webflux/src/main/java/graphql/spring/web/reactive/components/GraphQLController.java#L65

**Comment by marceloverdijk** [comment]
@gysbtzs2008 this should be fixed with https://github.com/graphql-java/graphql-java-spring/pull/13

**Comment by andimarek** [comment]
This project is now archived in favor of the official [Spring GraphQL](https://github.com/graphql-java/graphql-java-spring) integration.
