### ISSUE TITLE
Can we expect integration with Spring Security?

### ISSUE THREAD

**Issue by gnom7** [graphql-java/graphql-java-spring#2]
Can we implement some sort of integration with spring security? I think it might look like special GraphQL mutation, witch will be handled by library. The problem is that I cannot configure app using existing '..ConfigurerAdapter's since they rely on filters and with GraphQL we always have one endpoint.
I'd like to avoid manual authentication on home grown mutation.

**Comment by andimarek** [comment]
can you explain a bit more in detail what kind of support you would expect?

thanks

**Comment by andimarek** [comment]
closing because no response

**Comment by darkrift** [comment]
Can we reopen this ? 

I wanted to use webflux but cannot seem to be able to accomplish the easiness of spring object mapping that graphql-spring-boot-starter 5.0.2 provided plus the fact that I can't seem to be able to configure the security on the graphql endpoint as well.

For instance, a pretty basic use case would be to only allow authenticated user to the graphql endpoint. Right now, I use a normal rest endpoint to control my authentication flow (login, logout, roles access, etc) and only once he is logged in would I want the user to access graphql queries and mutations.

If it can be achieved with spring security, maybe a note or wiki page on how to do it would help
