### ISSUE TITLE
Add functional routing to integrate this library with spring-fu

### ISSUE THREAD

**Issue by pull-vert** [graphql-java/graphql-java-spring#25]
Now spring boot 2.2.0 has turned GA, spring-fu released related 0.2.1. Can you take a look at #18, it would allow graphql-java-spring to be used in spring-fu project.

**Comment by andimarek** [comment]
This project is now archived in favor of the official [Spring GraphQL](https://github.com/graphql-java/graphql-java-spring) integration.
