### ISSUE TITLE
Please, Release with DataLoader

### ISSUE THREAD

**Issue by etienne-sf** [graphql-java/graphql-java-spring#26]
Hello,

  You've merged the pull request from marceloverdijk.

This allows to use DataLoader with Spring Boot. Very interesting !

Please publish a release, so we can use it for our builds.

Etienne

**Comment by luissantos** [comment]
This implementation doesn't work. Dataloaders cannot be shared across threads. 
More details: https://github.com/graphql-java/graphql-java-spring/issues/21

**Comment by etienne-sf** [comment]
Yes, I understand this.

But it's very needed. I have a proposal, that I'll propose in a dedicated issue.
