### ISSUE TITLE
Incorrect handling of POST query param

### ISSUE THREAD

**Issue by nowicki-maciej** [graphql-java/graphql-java-spring#33]
In `graphql-java-spring-webmvc`, `GraphQLController.java`, when request has content type of `application/json`  and contains query parameter, it is not handled, as following `if` statement is trying to parse request body (which is null in this case):
https://github.com/graphql-java/graphql-java-spring/blob/c6606f624d98b0835e719e0d48ab7223b141cd19/graphql-java-spring-webmvc/src/main/java/graphql/spring/web/servlet/components/GraphQLController.java#L79

Is this correct behavior? According to [this article](https://graphql.org/learn/serving-over-http/#post-request) it is not said that `application/json` cannot be used with query parameter.

**Comment by andimarek** [comment]
This project is now archived in favor of the official [Spring GraphQL](https://github.com/graphql-java/graphql-java-spring) integration.
