### ISSUE TITLE
Do Not Support Subscriptions Autoconfigure

### ISSUE THREAD

**Issue by tq02ksu** [graphql-java/graphql-java-spring#34]
The project can autoconfigure graphqlController, provides an rest mapping of /graphql be default. It is great for my project, save me lot of code.

Recently, I want to write a subscription to monitor changes from server. I checked out the source code and related artifacts about spring-boot-starter of graphql.

I founded com.graphql-java:graphql-spring-boot-starter:5.0.2 can do that, but that uses an old graphql-java core dependency version released around 2018. Which have not more newer version, and have unofficial package name in source code, so I think it is likely be DEPRECATED? or retired? 

And graphql-java-spring likely the official "starter" project, but have no subscriptions support, any other friends meet the similar problems?

**Comment by lburja** [comment]
The new location for the old com.graphql-java:graphql-spring-boot-starter:5.0.2 is https://github.com/graphql-java-kickstart
