### ISSUE TITLE
Add support for application/graphql content type and post query params

### ISSUE THREAD

**Issue by marceloverdijk** [graphql-java/graphql-java-spring#4]
As stated in https://graphql.org/learn/serving-over-http/ besides the 'normal' `GET` and `POST` requests the following is recommended:

> * If the "query" query string parameter is present (as in the GET example above), it should be parsed and handled in the same way as the HTTP GET case.
> * If the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

If interested I can create a PR for this. Let me know.

Note: in the Micronaut integration lib we are doing the same: https://github.com/micronaut-projects/micronaut-graphql/blob/master/graphql/src/main/java/io/micronaut/graphql/GraphQLController.java#L116-L178

**Comment by andimarek** [comment]
yes, I think having this also supported would be great... thanks a lot.

**Comment by marceloverdijk** [comment]
@andimarek this one can be closed now.

**Comment by ryonday** [comment]
Is this going to make it into a release?

**Comment by marceloverdijk** [comment]
@ryonday this is already merged to `master` and will be included in the next release.

**Comment by andimarek** [comment]
solved via #4
