### ISSUE TITLE
Spring boot version upgrade

### ISSUE THREAD

**Issue by tomasz-galuszka** [graphql-java/graphql-java-spring#40]
Hello,
Are there any plans to upgrade to the latest spring boot version ? 
Existing version:  2.1.5.RELEASE (May 2019)

I know spring is moving very fast, but would be good to keep up to date with them - looks like we are +/- 50 releases behind.

**Comment by andimarek** [comment]
This project is now archived in favor of the official [Spring GraphQL](https://github.com/graphql-java/graphql-java-spring) integration.
