### ISSUE TITLE
Can not acquire the query context(dataFetchingEnviornment) when implement 'GraphQLResolver' to handle query.

### ISSUE THREAD

**Issue by wuych96** [graphql-java/graphql-java-spring#41]
When I implement the interface 'GraphQLQueryResolver' to handle query request, the 'DataFetchingEnvironment' is not provided. Thus I must configure a spring 'GraphQL' bean to register a data fetcher to get the enviornment. Has there any shortcuts please?

**Comment by andimarek** [comment]
This project is now archived in favor of the official [Spring GraphQL](https://github.com/graphql-java/graphql-java-spring) integration.
