### ISSUE TITLE
Customize ObjectMapper / inject custom ObjectMapper

### ISSUE THREAD

**Issue by benneq** [graphql-java/graphql-java-spring#6]
Currently the default Spring ObjectMapper is injected.

But in many applications it is already widely used and cannot be customized for graphql.

In my case a legacy app uses ObjectMapper with `setSerializationInclusion(Include.NON_NULL)`. This will break lot's of graphql clients. But I can't change it, because a lot of stuff within the legacy app relies on that behavior.

**Comment by marceloverdijk** [comment]
Similar as https://github.com/graphql-java-kickstart/graphql-java-servlet/issues/42

Maybe something like a `GraphQLObjectMapperProvider` interface can be introduced which has a `GraphQLObjectMapperProvider` implementation that simply takes the general `ObjectMapper` in the application context.

**Comment by jsdevel** [comment]
yea, there really shouldn't be a hardcoded objectMapper.  I'm attempting to implement this in hybris, and am not able to use the Jackson object mapper.

**Comment by marceloverdijk** [comment]
For [Micronaut-GraphQL](https://github.com/micronaut-projects/micronaut-graphql) we introduced a `GraphQLJsonSerializer` abstraction.
Maybe this could inspire `graphql-java-spring` as well. See https://github.com/micronaut-projects/micronaut-graphql/commit/9a51982a8de01d906216dfa834dae97ed6b3a41c for details.

**Comment by andimarek** [comment]
I like the Serializer abstraction mentioned by @marceloverdijk, I think this is the way to go. Anyone interested in creating a PR? @marceloverdijk @jsdevel @benneq ?

**Comment by marceloverdijk** [comment]
@andimarek I will provide a PR this week.

**Comment by andimarek** [comment]
@marceloverdijk thanks a lot

**Comment by andimarek** [comment]
solved via #10

**Comment by jsdevel** [comment]
@andimarek when will 2.0 be released?
