### ISSUE TITLE
Add support for subscriptions

### ISSUE THREAD

**Issue by marceloverdijk** [graphql-java/graphql-java-spring#7]

**Comment by andimarek** [comment]
@marceloverdijk what kind of support do you expect? how should the transport layer look like?

**Comment by marceloverdijk** [comment]
@andimarek most likely websockets.

**Comment by priyankpat** [comment]
Using server-sent events

**Comment by etienne-sf** [comment]
Any news on this subject ?

I found no way to make subscription work with graphql-java-spring-boot-starter-webmvc.

**_I there any documentation or hint on how to do it ??_**



My last try is to adapt the https://github.com/graphql-java/graphql-java-examples/tree/master/subscription-example.
But I got stuck.
I'm just unable to have subscription work when graphql-java-spring-boot-starter-webmvc is a dependency in the project.
The graphql.spring.web.servlet.components.GraphQLController takes the request with its graphqlGET, and complains that the query parameter is not there.

Everything works fine if the subscription is available on a separated URL. But of course, it's not GraphQL compliant.

Etienne

**Comment by etienne-sf** [comment]
For those interested, I succeeded in implementing it in a plugin that generates the code to do this, both on client and server side.

You can take a look here: https://github.com/graphql-java-generator/graphql-maven-plugin-project 

Etienne
